"""
Generate sythetic patient events from an aggregated tree of patient data.
HOW TO USE: python parcourVis.py parcourVis.json 2000 --output parcourVis2000.csv to generate 2000 patients from the data in parcourVis.json and save the result in parcourVis.csv
"""
import json
import sys
import csv
import random
import bz2
import math
from datetime import date, timedelta
from itertools import accumulate
from functools import reduce

from typing import Dict, Union, Any, List, Optional, Callable, cast, Tuple

JSon = Dict[str, Any]

random.seed(0)

def printDocAndExit():
    print("Run ./generate.py [data.json] [n_patients] [--output CSVOutput] [-h] [--help]")
    print("data.json: the aggregated JSON data generated by aggregate.py. Default: working_directory/data/data.json")
    print("n_patients: the number of synthetic patients to generate. Default: 100")
    print("--output: output path to save the generated CSV data to be preparsed by the ParcoursVis preparser. Default: the standard output")
    print("-h --help: Print this documentation and exit.")

    sys.exit(-1)


class _CSVWriter:
    def writerow(self, row: List[Union[None, int, float, str]]) -> None:
        pass

    def writerows(self, rows: List[List[Union[None, int, float, str]]]) -> None:
        pass

    def dialect(self) -> csv.Dialect:
        pass


MIN_DATE = date(2000, 1, 1)
MAX_DATE = date(2018, 12, 31)


def load_dataset(filename: str) -> JSon:
    "Load a dataset in json format, potentially bzip2 compressed."
    fopen: Any = open
    if filename.endswith(".bz2"):
        fopen = bz2.open
    with fopen(filename, "rb") as istream:
        return cast(JSon, json.load(istream))


def weighted_choice(cum_weights: List[float]) -> int:
    "Return a random value given a list of cumulative sum of weights"
    rand = random.uniform(sys.float_info.min, cum_weights[-1])
    for index, cum_weight in enumerate(cum_weights):
        if rand <= cum_weight:
            return index
    assert False, "Shouldn't get here"
    return -1


def weighted_average(weights: List[float], min_: float, max_: float) -> float:
    "Return the weighted average, given a histogram and is bounds."
    width: float = (max_ - min_ + 1) / len(weights)
    cum_sum: float = 0
    cum_count: float = 0
    value: float = min_ + width / 2
    for weight in weights:
        cum_sum += weight * value
        cum_count += weight
        value += width
    return cum_sum / cum_count


def weighted_measure(measure: Optional[Dict[str, Any]]) -> Optional[float]:
    "Return a random value generated with a distribution given by a histogram."
    if measure is None:
        return None
    weights: List[float] = measure.get("bins", [])
    range_: Tuple[float, float] = measure.get("range", [0, 1])
    min_ = range_[0]
    max_ = range_[1]
    width: float = (max_ - min_) / len(weights)
    if width == 0:
        width = 1/len(weights)
    cum_weights = list(accumulate(weights))
    rand = weighted_choice(cum_weights)
    return (
        (rand + random.uniform(0, 1)) * width + min_
    )  # return the center of the bin


def generate_death(
    csvfile: _CSVWriter,
    pid: int,
    start_date: date,
    event: str,
    age: int,
    time: float,
    diseases: str
) -> None:
    "Generate a death event in the CSV file."
    csvfile.writerow([pid, age, event, start_date.isoformat(), None, diseases])


DRUGS = {
    "alphabloc": [
        "doxazosine",
        "alfuzosine",
        "dysalfa",
        "hytrine",
        "josir",
        "mecir",
        "minipress",
        "omexel",
        "omix",
        "silodyx",
        "tamulosine",
        "térazosine",
        "urion",
        "urorec",
        "xatral",
        "zoxan",
    ],
    "fivealpha": ["avodart", "chibro-proscar", "dutastéride", "finastéride"],
    "phyto": ["palmier de floride biogaran", "permixon", "prodinan", "tadenan"],
}

def generate_treatment(
    # csvfile, pid, start_date, event, age, time, diseases):
    csvfile: _CSVWriter,
    pid: int,
    start_date: date,
    event: str,
    age: int,
    time: float,
    diseases: str
) -> None:
    "Generate many treatment events in the CSV file. For now, every week approximately."
    drugs: Dict[str, str] = {}
    events   = event.split(" ")
    nbRepeat = math.ceil(time/7)
    
    dtime = 0
    random.shuffle(events)
    for n in range(0, nbRepeat):
        curdate = start_date + timedelta(days=int(dtime))
        dtime += 7
        if dtime > time:
            dtime = time
        for i in range(len(events)):
            ev = events[i]
            if ev in drugs:
                drug = drugs[ev]
            else:
                drug = random.choice(DRUGS[ev])
                drugs[ev] = drug

            csvfile.writerow([pid, age, ev, curdate.isoformat(), drug, diseases])

# Old source code. Does not take into account compound events...
#    for dtime in range(0, int(time) + 7, 7):
#        curdate = start_date + timedelta(days=dtime)
#        ev = random.choice(events)
#        if ev in drugs:
#            drug = drugs[ev]
#        else:
#            drug = random.choice(DRUGS[ev])
#            drugs[ev] = drug
#
#        csvfile.writerow([pid, age, ev, curdate.isoformat(), drug, diseases])


def generate_no_treatment(
    # *args):  # csvfile, pid, start_date, event, age, time):
    csvfile: _CSVWriter,
    pid: int,
    start_date: date,
    event: str,
    age: int,
    time: float,
    diseases: str
) -> None:
    """
    Generate an event for no treatment.

    Actually, no event is generated, only the time is updated
    to express a delay interpreted as no treatment.
    """
    # csvfile.writerow([pid, age, event, start_date.isoformat(), None])
    pass


def generate_surgery(
    csvfile: _CSVWriter,
    pid: int,
    start_date: date,
    event: str,
    age: int,
    time: float,
    diseases: str
) -> None:
    "Generate a surgery event."
    csvfile.writerow([pid, age, event, start_date.isoformat(), None, diseases])


def generate_interruption(
    csvfile: _CSVWriter,
    pid: int,
    start_date: date,
    event: str,
    age: int,
    time: float,
    diseases: str
) -> None:
    """
    Generate an event for treatment interruption.

    Actually, no event is generated, only the time is updated
    to express a delay interpreted as treatment interruption.
    """
    # csvfile.writerow([pid, age, event, start_date.isoformat(), None])
    pass


SWITCH: Dict[str,
             Callable[[_CSVWriter, int, date, str, int, float, str], None]] = {
    "interruption": generate_interruption,
    "death": generate_death,
    "alphabloc": generate_treatment,
    "fivealpha": generate_treatment,
    "fivealpha alphabloc": generate_treatment,
    "alphabloc phyto": generate_treatment,
    "surgery": generate_surgery,
    "fivealpha alphabloc phyto": generate_treatment,
    "no treatment": generate_no_treatment,
    "phyto": generate_treatment,
}


def generate(csvfile: _CSVWriter, pid: int, node: Dict[str, Any]) -> None:
    #TODO: Handle the generation of not one disease per patients but of multiple diseases per patients
    events = generate_events(node)
    if len(events) == 0: #This special case can happen because of the threshold set by aggregate.py: The root node can have more "individuals" than the sum of its children count
        return False

    # take the age from the distribution of the last event
    last_disease = ""
    last_event = events[-1]
    last_age = weighted_measure(last_event["node"].get("age_histogram"))
    diseases = last_event["node"].get("disease_barchart", [])
    count = last_event["node"].get("count")
    for cur_disease in diseases:
        rand_count = random.randrange(count)
        if (rand_count < cur_disease['value']):
            if len(last_disease) > 0:
                last_disease += " "
            last_disease += cur_disease['name']

    for event in reversed(events):
        time = weighted_measure(event["node"].get("duration_histogram"))
        event["time"] = time
        category = event["category"]
        if category == "no treatment":
            event["time"] = max(time, 360)
        elif category == "interruption":
            event["time"] = max(time, 180)
        event["age"] = last_age
        last_age -= time / 365.25
        # if last_age is None:
        #     import pdb
        #     pdb.set_trace()
        event["diseases"] = last_disease
        # TODO: update the list of deseases

    rand_date = random.uniform(MIN_DATE.toordinal(), MAX_DATE.toordinal())
    start_date = date.fromordinal(int(rand_date))

    for event in events:
        generate_node(csvfile, pid, start_date, event)
        if "time" in event:
            start_date += timedelta(days=event["time"])

    return True


def generate_events(node: JSon) -> List[Dict[str, Any]]:
    events = []
    while node:
        count = node.get("count", 0)
        if count == 0:
            break
        children = node.get("children", None)
        if children is None:
            break
        weights = [cnt.get("count", 0) for cnt in children]
        cum_weights = list(accumulate(weights))
        cum_weights.append(count)
        # print('cum_weights=', cum_weights)
        rand = weighted_choice(cum_weights)
        if rand >= len(children):
            break
        node = children[rand]
        event = {"category": node["name"], "node": node}
        events.append(event)
    return events


def generate_node(csvfile: _CSVWriter,
                  pid: int,
                  start_date: date,
                  event: Dict[str, Any]) -> None:
    fn = SWITCH.get(event["category"])
    if fn:
        fn(
            csvfile,
            pid,
            start_date,
            str(event["category"]),
            int(event["age"]),
            cast(float, event.get("time")),
            str(event.get("diseases")),
        )
    else:
        assert False, "Received event %s: Shouldn't get here" % event


if __name__ == "__main__":
    random.seed(42)
    repeat     = 100
    argv       = sys.argv[1:]
    jsonData   = "parcourVis.json"
    files      = []
    outputFile = sys.stdout

    i = 0
    while i < len(argv):
        #Read input file names (beginning of the command)
        arg = argv[i]
        if arg.startswith("--") or arg.startswith("-"):
            while i < len(argv):
                arg = argv[i]

                if arg == "-h" or arg == "--help":
                    printDocAndExit()

                elif arg == "--output":
                    if i < len(argv)-1:
                        try:
                            outputFile = open(argv[i+1], "w")
                        except IOError:
                            print(f"Cannot open the file {argv[i+1]}. Exiting")
                            sys.exit(-1)
                        i+=1
                    else:
                        print("Missing CSV file path value to '--output' parameter")
                        sys.exit(-1)
                else:
                    print("Unknown parameter {}".format(arg))
                    printDocAndExit()
                i+=1
        elif i == 0:
            jsonData = arg
            i+=1
        elif i == 1:
            repeat = int(arg)
            i+=1

    jsonData = load_dataset(jsonData)

    try:
        writer = cast(_CSVWriter, csv.writer(outputFile))
        writer.writerow([
            "NUM_ENQ", "age", "category", "date", "drug", "Other Diseases"
        ])
        for i in range(repeat):
            if i != 0 and i % 10000 == 0:
                sys.stderr.write(str(i) + " individuals have been generated.\n")

            while not generate(writer, i, jsonData): #There are special cases where generate cannot generate an individual. Retry again
                pass
    except IOError:
        print("Input/Output error. Aborting")

    #Close the opened file
    if outputFile != sys.stdout:
        outputFile.close()
